// <auto-generated />
using System;
using AOIOpsPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AOIOpsPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AoiOpsDbContext))]
    partial class AoiOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AlarmCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alarm_code");

                    b.Property<string>("AlarmLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("alarm_level");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cleared_at");

                    b.Property<string>("LineCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("line_code");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("message");

                    b.Property<string>("OperatorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("operator_name");

                    b.Property<string>("PanelNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<Guid?>("ProcessRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("process_run_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("StationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tool_id");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id");

                    b.HasIndex("LotNo");

                    b.HasIndex("OperatorCode");

                    b.HasIndex("PanelNo");

                    b.HasIndex("ProcessRunId");

                    b.HasIndex("StationCode");

                    b.HasIndex("ToolCode");

                    b.HasIndex("ToolId");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("alarms", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.CopilotQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("query_text");

                    b.Property<Guid?>("RelatedAlarmId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("related_alarm_id");

                    b.Property<Guid?>("RelatedDefectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("related_defect_id");

                    b.Property<string>("SourceRefs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_refs");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RelatedAlarmId");

                    b.HasIndex("RelatedDefectId");

                    b.ToTable("copilot_queries", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DefectCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("defect_code");

                    b.Property<string>("DefectType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("defect_type");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("detected_at");

                    b.Property<bool>("IsFalseAlarm")
                        .HasColumnType("bit")
                        .HasColumnName("is_false_alarm");

                    b.Property<string>("KafkaEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("kafka_event_id");

                    b.Property<string>("LineCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("line_code");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lot_id");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<string>("OperatorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("operator_name");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("panel_id");

                    b.Property<string>("PanelNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<Guid?>("ProcessRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("process_run_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("StationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tool_id");

                    b.Property<decimal?>("XCoord")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("x_coord");

                    b.Property<decimal?>("YCoord")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("y_coord");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("LotId");

                    b.HasIndex("LotNo");

                    b.HasIndex("OperatorCode");

                    b.HasIndex("PanelId");

                    b.HasIndex("PanelNo");

                    b.HasIndex("ProcessRunId");

                    b.HasIndex("StationCode");

                    b.HasIndex("ToolCode");

                    b.HasIndex("ToolId");

                    b.ToTable("defects", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.DefectImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DefectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("defect_id");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("image_path");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("thumbnail_path");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.ToTable("defect_images", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.DefectReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("DefectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("defect_id");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("review_comment");

                    b.Property<string>("ReviewResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("review_result");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reviewer");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.ToTable("defect_reviews", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DocType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("doc_type");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("source_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chunk_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("EmbeddingId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("embedding_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("line_code");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("line_name");

                    b.HasKey("Id");

                    b.HasIndex("LineCode")
                        .IsUnique();

                    b.ToTable("lines", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("end_time");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("product_code");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LotNo")
                        .IsUnique();

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.MaterialLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("MaterialLotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("material_lot_no");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("material_name");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("material_type");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("supplier");

                    b.HasKey("Id");

                    b.HasIndex("MaterialLotNo")
                        .IsUnique();

                    b.HasIndex("MaterialType");

                    b.ToTable("material_lots", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("operator_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Shift")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("shift");

                    b.HasKey("Id");

                    b.HasIndex("OperatorCode")
                        .IsUnique();

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lot_id");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<string>("PanelNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("LotNo");

                    b.HasIndex("PanelNo")
                        .IsUnique();

                    b.ToTable("panels", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.PanelMaterialUsage", b =>
                {
                    b.Property<Guid>("PanelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("panel_id");

                    b.Property<Guid>("MaterialLotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("material_lot_id");

                    b.Property<string>("MaterialLotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("material_lot_no");

                    b.Property<string>("PanelNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("used_at");

                    b.HasKey("PanelId", "MaterialLotId");

                    b.HasIndex("MaterialLotId");

                    b.HasIndex("MaterialLotNo");

                    b.HasIndex("PanelNo");

                    b.ToTable("panel_material_usage", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.PanelStationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("entered_at");

                    b.Property<DateTimeOffset?>("ExitedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("exited_at");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Operator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("operator");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("operator_name");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("panel_id");

                    b.Property<string>("PanelNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("result");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("ToolCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.HasKey("Id");

                    b.HasIndex("PanelNo");

                    b.HasIndex("StationCode");

                    b.HasIndex("PanelId", "EnteredAt");

                    b.ToTable("panel_station_log", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Lsl")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("lsl");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("parameter_code");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("parameter_name");

                    b.Property<decimal>("Target")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("target");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Usl")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("usl");

                    b.HasKey("Id");

                    b.HasIndex("ParameterCode")
                        .IsUnique();

                    b.ToTable("parameters", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.ProcessRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lot_id");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("panel_id");

                    b.Property<string>("PanelNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("pressure");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("result_status");

                    b.Property<DateTimeOffset?>("RunEndAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("run_end_at");

                    b.Property<DateTimeOffset>("RunStartAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("run_start_at");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("temperature");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tool_id");

                    b.Property<decimal?>("YieldRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("yield_rate");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("LotNo");

                    b.HasIndex("PanelId");

                    b.HasIndex("PanelNo");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RunStartAt");

                    b.HasIndex("ToolCode");

                    b.HasIndex("ToolId");

                    b.ToTable("process_runs", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("recipe_code");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("recipe_name");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCode")
                        .IsUnique();

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.SpcMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsViolation")
                        .HasColumnType("bit")
                        .HasColumnName("is_violation");

                    b.Property<string>("KafkaEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("kafka_event_id");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("line_code");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("measured_at");

                    b.Property<string>("OperatorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("operator_name");

                    b.Property<Guid?>("PanelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("panel_id");

                    b.Property<string>("PanelNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("parameter_code");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parameter_id");

                    b.Property<string>("StationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tool_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("value");

                    b.Property<string>("ViolationCodes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("violation_codes");

                    b.HasKey("Id");

                    b.HasIndex("IsViolation");

                    b.HasIndex("PanelId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("ToolId");

                    b.HasIndex("LineCode", "MeasuredAt");

                    b.HasIndex("PanelNo", "MeasuredAt");

                    b.HasIndex("ParameterCode", "MeasuredAt");

                    b.HasIndex("ToolCode", "MeasuredAt");

                    b.ToTable("spc_measurements", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("station_name");

                    b.HasKey("Id");

                    b.HasIndex("StationCode")
                        .IsUnique();

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("LineCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("line_code");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("line_id");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_type");

                    b.HasKey("Id");

                    b.HasIndex("LineCode");

                    b.HasIndex("LineId");

                    b.HasIndex("ToolCode")
                        .IsUnique();

                    b.ToTable("tools", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Workorder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DefectCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("defect_code");

                    b.Property<string>("LineCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("line_code");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lot_id");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lot_no");

                    b.Property<string>("OperatorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("operator_name");

                    b.Property<Guid?>("PanelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("panel_id");

                    b.Property<string>("PanelNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("panel_no");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("priority");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceQueue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source_queue");

                    b.Property<string>("StationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("ToolCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tool_code");

                    b.Property<Guid?>("ToolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tool_id");

                    b.Property<string>("WorkorderNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("workorder_no");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("LotNo");

                    b.HasIndex("OperatorCode");

                    b.HasIndex("PanelId");

                    b.HasIndex("PanelNo");

                    b.HasIndex("StationCode");

                    b.HasIndex("ToolCode");

                    b.HasIndex("ToolId");

                    b.HasIndex("WorkorderNo")
                        .IsUnique();

                    b.ToTable("workorders", (string)null);
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Alarm", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.ProcessRun", "ProcessRun")
                        .WithMany("Alarms")
                        .HasForeignKey("ProcessRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Tool", "Tool")
                        .WithMany("Alarms")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessRun");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.CopilotQuery", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Alarm", "RelatedAlarm")
                        .WithMany()
                        .HasForeignKey("RelatedAlarmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Defect", "RelatedDefect")
                        .WithMany()
                        .HasForeignKey("RelatedDefectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedAlarm");

                    b.Navigation("RelatedDefect");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Defect", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Lot", "Lot")
                        .WithMany("Defects")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Panel", "Panel")
                        .WithMany("Defects")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.ProcessRun", "ProcessRun")
                        .WithMany("Defects")
                        .HasForeignKey("ProcessRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Tool", "Tool")
                        .WithMany("Defects")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("Panel");

                    b.Navigation("ProcessRun");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.DefectImage", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Defect", "Defect")
                        .WithMany("Images")
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.DefectReview", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Defect", "Defect")
                        .WithMany("Reviews")
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Panel", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Lot", "Lot")
                        .WithMany("Panels")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.PanelMaterialUsage", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.MaterialLot", "MaterialLot")
                        .WithMany("Usages")
                        .HasForeignKey("MaterialLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Panel", "Panel")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialLot");

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.PanelStationLog", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Panel", "Panel")
                        .WithMany("StationLogs")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Station", "Station")
                        .WithMany("StationLogs")
                        .HasForeignKey("StationCode")
                        .HasPrincipalKey("StationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Panel");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.ProcessRun", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Lot", "Lot")
                        .WithMany("ProcessRuns")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Panel", "Panel")
                        .WithMany("ProcessRuns")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Recipe", "Recipe")
                        .WithMany("ProcessRuns")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Tool", "Tool")
                        .WithMany("ProcessRuns")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("Panel");

                    b.Navigation("Recipe");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.SpcMeasurement", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Panel", "Panel")
                        .WithMany("SpcMeasurements")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Parameter", "Parameter")
                        .WithMany("Measurements")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Tool", "Tool")
                        .WithMany("SpcMeasurements")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Panel");

                    b.Navigation("Parameter");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Tool", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Line", "Line")
                        .WithMany("Tools")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Line");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Workorder", b =>
                {
                    b.HasOne("AOIOpsPlatform.Domain.Entities.Lot", "Lot")
                        .WithMany("Workorders")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AOIOpsPlatform.Domain.Entities.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Lot");

                    b.Navigation("Panel");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Defect", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Line", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Lot", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("Panels");

                    b.Navigation("ProcessRuns");

                    b.Navigation("Workorders");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.MaterialLot", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Panel", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("MaterialUsages");

                    b.Navigation("ProcessRuns");

                    b.Navigation("SpcMeasurements");

                    b.Navigation("StationLogs");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Parameter", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.ProcessRun", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Defects");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("ProcessRuns");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Station", b =>
                {
                    b.Navigation("StationLogs");
                });

            modelBuilder.Entity("AOIOpsPlatform.Domain.Entities.Tool", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Defects");

                    b.Navigation("ProcessRuns");

                    b.Navigation("SpcMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
